# Profile
spring:
  config:
    activate:
      on-profile: prod

  # file
  servlet:
    multipart:
      max-file-size: 10MB

  # session
  session:
    store-type: redis

# logging
logging:
  file:
    path: logs
    name: market-gola-api
